In [13]:
import pandas as pd

# Ajuster les paramètres pour afficher toutes les lignes et colonnes
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

df1 = pd.read_csv(
    "../data/LFB Incident data from 2009 - 2017.csv", sep=",", low_memory=False
)
df2 = pd.read_csv(
    "../data/LFB Incident data from 2018 onwards.csv", sep=",", low_memory=False
)

In [14]:
# display(df1.info())
# display(df2.info())
# print(df2.columns)
# print(df2.columns)

In [15]:
df = pd.concat([df1, df2], axis=0)
df = df.reset_index(drop=True)

print(df.shape)
display(df.head(2))

# suppression des .00
df["IncidentNumber"] = df["IncidentNumber"].apply(
    lambda x: str(x)[0:-3] if (".00" in x) & (str(x)[-3:] == ".00") else x
)

df.DateOfCall = pd.to_datetime(df.DateOfCall, format="%d-%b-%y")
df.TimeOfCall = pd.to_datetime(df.TimeOfCall, format="%H:%M:%S")

df["Month"] = df["DateOfCall"].dt.month
df["DayOfWeek"] = df["DateOfCall"].dt.dayofweek
df["DayName"] = df["DateOfCall"].dt.day_name()

display(df.head())
display(df.info())
display(df.describe())

(1771413, 39)

,IncidentNumber,DateOfCall,CalYear,TimeOfCall,HourOfCall,IncidentGroup,StopCodeDescription,SpecialServiceType,PropertyCategory,PropertyType,AddressQualifier,Postcode_full,Postcode_district,UPRN,USRN,IncGeo_BoroughCode,IncGeo_BoroughName,ProperCase,IncGeo_WardCode,IncGeo_WardName,IncGeo_WardNameNew,Easting_m,Northing_m,Easting_rounded,Northing_rounded,Latitude,Longitude,FRS,IncidentStationGround,FirstPumpArriving_AttendanceTime,FirstPumpArriving_DeployedFromStation,SecondPumpArriving_AttendanceTime,SecondPumpArriving_DeployedFromStation,NumStationsWithPumpsAttending,NumPumpsAttending,PumpCount,PumpMinutesRounded,Notional Cost (£),NumCalls
0,235138081.00,01-Jan-09,2009,00:00:37,0,Special Service,Special Service,RTC,Road Vehicle,Car,In street close to gazetteer location,SW11 4LB,SW11,NaN,NaN,E09000032,WANDSWORTH,Wandsworth,E05014010,Battersea Park,Battersea Park,528652.0,176830.0,528650,176850,51.475812,-0.148894,London,Battersea,319.0,Battersea,342.0,Clapham,2.0,2.0,2,60,255,1.0
1,1091.00,01-Jan-09,2009,00:00:46,0,Special Service,Special Service,Assist other agencies,Outdoor,Lake/pond/reservoir,Open land/water - nearest gazetteer location,SE1 7SG,SE1,NaN,NaN,E09000022,LAMBETH,Lambeth,E05014118,Waterloo & South Bank,Waterloo & South Bank,530485.0,179007.0,530450,179050,51.494957,-0.121712,London,Lambeth,NaN,NaN,NaN,NaN,NaN,NaN,1,60,255,1.0

,IncidentNumber,DateOfCall,CalYear,TimeOfCall,HourOfCall,IncidentGroup,StopCodeDescription,SpecialServiceType,PropertyCategory,PropertyType,AddressQualifier,Postcode_full,Postcode_district,UPRN,USRN,IncGeo_BoroughCode,IncGeo_BoroughName,ProperCase,IncGeo_WardCode,IncGeo_WardName,IncGeo_WardNameNew,Easting_m,Northing_m,Easting_rounded,Northing_rounded,Latitude,Longitude,FRS,IncidentStationGround,FirstPumpArriving_AttendanceTime,FirstPumpArriving_DeployedFromStation,SecondPumpArriving_AttendanceTime,SecondPumpArriving_DeployedFromStation,NumStationsWithPumpsAttending,NumPumpsAttending,PumpCount,PumpMinutesRounded,Notional Cost (£),NumCalls,Month,DayOfWeek,DayName
0,235138081,2009-01-01,2009,1900-01-01 00:00:37,0,Special Service,Special Service,RTC,Road Vehicle,Car,In street close to gazetteer location,SW11 4LB,SW11,NaN,NaN,E09000032,WANDSWORTH,Wandsworth,E05014010,Battersea Park,Battersea Park,528652.0,176830.0,528650,176850,51.475812,-0.148894,London,Battersea,319.0,Battersea,342.0,Clapham,2.0,2.0,2,60,255,1.0,1,3,Thursday
1,1091,2009-01-01,2009,1900-01-01 00:00:46,0,Special Service,Special Service,Assist other agencies,Outdoor,Lake/pond/reservoir,Open land/water - nearest gazetteer location,SE1 7SG,SE1,NaN,NaN,E09000022,LAMBETH,Lambeth,E05014118,Waterloo & South Bank,Waterloo & South Bank,530485.0,179007.0,530450,179050,51.494957,-0.121712,London,Lambeth,NaN,NaN,NaN,NaN,NaN,NaN,1,60,255,1.0,1,3,Thursday
2,2091,2009-01-01,2009,1900-01-01 00:03:00,0,Fire,Secondary Fire,NaN,Outdoor,Road surface/pavement,In street outside gazetteer location,N9 9EL,N9,NaN,NaN,E09000010,ENFIELD,Enfield,E05013682,Haselbury,Haselbury,533773.0,194492.0,533750,194450,51.633342,-0.068488,London,Edmonton,308.0,Edmonton,NaN,NaN,1.0,1.0,1,60,255,2.0,1,3,Thursday
3,3091,2009-01-01,2009,1900-01-01 00:04:27,0,Fire,Secondary Fire,NaN,Outdoor,Domestic garden (vegetation not equipment),On land associated with building,UB10 0DG,UB10,1.000215e+11,21401491.0,E09000017,HILLINGDON,Hillingdon,E05013571,Hillingdon East,Hillingdon East,507738.0,182805.0,507750,182850,51.533882,-0.448089,London,Hillingdon,210.0,Hillingdon,NaN,NaN,1.0,1.0,1,60,255,2.0,1,3,Thursday
4,5091,2009-01-01,2009,1900-01-01 00:05:39,0,Fire,Secondary Fire,NaN,Outdoor,Cycle path/public footpath/bridleway,In street outside gazetteer location,N7 8HG,N7,NaN,NaN,E09000019,ISLINGTON,Islington,E05013708,Laycock,Laycock,531058.0,185307.0,531050,185350,51.551441,-0.111120,London,Holloway,233.0,Holloway,250.0,Holloway,1.0,2.0,2,60,255,1.0,1,3,Thursday

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1771413 entries, 0 to 1771412
Data columns (total 42 columns):
 #   Column                                  Dtype
---  ------                                  -----
 0   IncidentNumber                          object
 1   DateOfCall                              datetime64[ns]
 2   CalYear                                 int64
 3   TimeOfCall                              datetime64[ns]
 4   HourOfCall                              int64
 5   IncidentGroup                           object
 6   StopCodeDescription                     object
 7   SpecialServiceType                      object
 8   PropertyCategory                        object
 9   PropertyType                            object
 10  AddressQualifier                        object
 11  Postcode_full                           object
 12  Postcode_district                       object
 13  UPRN                                    float64
 14  USRN                                    float64
 15  IncGeo_BoroughCode                      object
 16  IncGeo_BoroughName                      object
 17  ProperCase                              object
 18  IncGeo_WardCode                         object
 19  IncGeo_WardName                         object
 20  IncGeo_WardNameNew                      object
 21  Easting_m                               float64
 22  Northing_m                              float64
 23  Easting_rounded                         int64
 24  Northing_rounded                        int64
 25  Latitude                                float64
 26  Longitude                               float64
 27  FRS                                     object
 28  IncidentStationGround                   object
 29  FirstPumpArriving_AttendanceTime        float64
 30  FirstPumpArriving_DeployedFromStation   object
 31  SecondPumpArriving_AttendanceTime       float64
 32  SecondPumpArriving_DeployedFromStation  object
 33  NumStationsWithPumpsAttending           float64
 34  NumPumpsAttending                       float64
 35  PumpCount                               int64
 36  PumpMinutesRounded                      int64
 37  Notional Cost (£)                       int64
 38  NumCalls                                float64
 39  Month                                   int32
 40  DayOfWeek                               int32
 41  DayName                                 object
dtypes: datetime64[ns](2), float64(11), int32(2), int64(7), object(20)
memory usage: 554.1+ MB

None

,DateOfCall,CalYear,TimeOfCall,HourOfCall,UPRN,USRN,Easting_m,Northing_m,Easting_rounded,Northing_rounded,Latitude,Longitude,FirstPumpArriving_AttendanceTime,SecondPumpArriving_AttendanceTime,NumStationsWithPumpsAttending,NumPumpsAttending,PumpCount,PumpMinutesRounded,Notional Cost (£),NumCalls,Month,DayOfWeek
count,1771413,1.771413e+06,1771413,1.771413e+06,1.630080e+06,1.608542e+06,886544.000000,886544.000000,1.771413e+06,1.771413e+06,886544.000000,886544.000000,1.635724e+06,633568.00000,1.757310e+06,1.757310e+06,1.771413e+06,1.771413e+06,1.771413e+06,1.769564e+06,1.771413e+06,1.771413e+06
mean,2016-12-16 06:27:20.863649024,2.016456e+03,1900-01-01 13:58:01.595983360,1.346887e+01,2.192842e+10,2.031355e+07,530632.668589,180365.050822,5.306598e+05,1.804883e+05,51.445867,-0.118837,3.182711e+02,395.38522,1.369216e+00,1.554288e+00,1.591798e+00,7.629298e+01,4.039678e+02,1.329551e+00,6.561727e+00,3.020437e+00
min,2009-01-01 00:00:00,2.009000e+03,1900-01-01 00:00:00,0.000000e+00,0.000000e+00,0.000000e+00,503582.000000,155901.000000,5.035500e+05,1.559500e+05,0.000000,-0.510155,1.000000e+00,1.00000,1.000000e+00,1.000000e+00,1.000000e+00,6.000000e+01,2.550000e+02,1.000000e+00,1.000000e+00,0.000000e+00
25%,2012-08-17 00:00:00,2.012000e+03,1900-01-01 09:51:06,9.000000e+00,0.000000e+00,2.040096e+07,525185.000000,175989.000000,5.252500e+05,1.761500e+05,51.468944,-0.197424,2.310000e+02,295.00000,1.000000e+00,1.000000e+00,1.000000e+00,6.000000e+01,2.600000e+02,1.000000e+00,4.000000e+00,1.000000e+00
50%,2017-01-04 00:00:00,2.017000e+03,1900-01-01 14:45:16,1.400000e+01,0.000000e+00,2.120127e+07,530797.000000,180982.000000,5.309500e+05,1.810500e+05,51.512881,-0.116981,2.960000e+02,369.00000,1.000000e+00,1.000000e+00,1.000000e+00,6.000000e+01,3.280000e+02,1.000000e+00,7.000000e+00,3.000000e+00
75%,2021-04-30 00:00:00,2.021000e+03,1900-01-01 19:02:12,1.900000e+01,1.001319e+10,2.210116e+07,536834.000000,184939.000000,5.362500e+05,1.851500e+05,51.547757,-0.028701,3.780000e+02,464.00000,2.000000e+00,2.000000e+00,2.000000e+00,6.000000e+01,3.640000e+02,1.000000e+00,9.000000e+00,5.000000e+00
max,2024-10-31 00:00:00,2.024000e+03,1900-01-01 23:59:59,2.300000e+01,2.000044e+11,9.999042e+07,561126.000000,200906.000000,6.111500e+05,3.024500e+05,51.691670,0.322219,1.200000e+03,1200.00000,4.600000e+01,1.060000e+02,9.510000e+02,5.256290e+05,2.277726e+06,3.690000e+02,1.200000e+01,6.000000e+00
std,NaN,4.776673e+00,NaN,6.252623e+00,4.753228e+10,4.378135e+06,10336.679483,7434.831140,9.725543e+03,7.357290e+03,1.775330,0.148994,1.386791e+02,153.33425,6.836639e-01,8.418938e-01,1.586884e+00,5.678902e+02,2.710555e+03,1.488664e+00,3.361091e+00,1.997067e+00

In [16]:
# display(df.isna().sum())
all_na = df.isna().sum()
lignes = df.shape[0]
print(lignes)
list = {}
list["colonne"] = []
list["na"] = []
list["pourcentage"] = []
for colonne, na in zip(all_na.index, all_na.values):
    pourcentage = round(na / lignes * 100, 4)
    list["colonne"].append(colonne)
    list["na"].append(na)
    list["pourcentage"].append(pourcentage)
    print(f"{na}, {pourcentage}%")
a = pd.DataFrame(list)
display(a)

1771413
0, 0.0%
0, 0.0%
0, 0.0%
0, 0.0%
0, 0.0%
6, 0.0003%
0, 0.0%
1195862, 67.5089%
6, 0.0003%
6, 0.0003%
1, 0.0001%
884869, 49.9527%
0, 0.0%
141333, 7.9785%
162871, 9.1944%
0, 0.0%
0, 0.0%
0, 0.0%
515, 0.0291%
515, 0.0291%
515, 0.0291%
884869, 49.9527%
884869, 49.9527%
0, 0.0%
0, 0.0%
884869, 49.9527%
884869, 49.9527%
0, 0.0%
1, 0.0001%
135689, 7.6599%
135700, 7.6606%
1137845, 64.2338%
1137852, 64.2341%
14103, 0.7961%
14103, 0.7961%
0, 0.0%
0, 0.0%
0, 0.0%
1849, 0.1044%
0, 0.0%
0, 0.0%
0, 0.0%

                                   colonne       na  pourcentage
0                           IncidentNumber        0       0.0000
1                               DateOfCall        0       0.0000
2                                  CalYear        0       0.0000
3                               TimeOfCall        0       0.0000
4                               HourOfCall        0       0.0000
5                            IncidentGroup        6       0.0003
6                      StopCodeDescription        0       0.0000
7                       SpecialServiceType  1195862      67.5089
8                         PropertyCategory        6       0.0003
9                             PropertyType        6       0.0003
10                        AddressQualifier        1       0.0001
11                           Postcode_full   884869      49.9527
12                       Postcode_district        0       0.0000
13                                    UPRN   141333       7.9785
14                                    USRN   162871       9.1944
15                      IncGeo_BoroughCode        0       0.0000
16                      IncGeo_BoroughName        0       0.0000
17                              ProperCase        0       0.0000
18                         IncGeo_WardCode      515       0.0291
19                         IncGeo_WardName      515       0.0291
20                      IncGeo_WardNameNew      515       0.0291
21                               Easting_m   884869      49.9527
22                              Northing_m   884869      49.9527
23                         Easting_rounded        0       0.0000
24                        Northing_rounded        0       0.0000
25                                Latitude   884869      49.9527
26                               Longitude   884869      49.9527
27                                     FRS        0       0.0000
28                   IncidentStationGround        1       0.0001
29        FirstPumpArriving_AttendanceTime   135689       7.6599
30   FirstPumpArriving_DeployedFromStation   135700       7.6606
31       SecondPumpArriving_AttendanceTime  1137845      64.2338
32  SecondPumpArriving_DeployedFromStation  1137852      64.2341
33           NumStationsWithPumpsAttending    14103       0.7961
34                       NumPumpsAttending    14103       0.7961
35                               PumpCount        0       0.0000
36                      PumpMinutesRounded        0       0.0000
37                       Notional Cost (£)        0       0.0000
38                                NumCalls     1849       0.1044
39                                   Month        0       0.0000
40                               DayOfWeek        0       0.0000
41                                 DayName        0       0.0000

In [17]:
for col in df.columns:
    uniques = df[col].unique()
    if len(uniques) < 15:
        print(col, uniques)

IncidentGroup ['Special Service' 'Fire' 'False Alarm' nan]
StopCodeDescription ['Special Service' 'Secondary Fire' 'AFA' 'Primary Fire'
 'False alarm - Good intent' 'False alarm - Malicious' 'Chimney Fire'
 'Flood call attended - Batch mobilised' 'Late Call'
 'Use of Special Operations Room' 'Standby']
PropertyCategory ['Road Vehicle' 'Outdoor' 'Dwelling' 'Outdoor Structure'
 'Other Residential' 'Non Residential' 'Aircraft' 'Rail Vehicle' 'Boat'
 nan]
AddressQualifier ['In street close to gazetteer location'
 'Open land/water - nearest gazetteer location'
 'In street outside gazetteer location' 'On land associated with building'
 'Correct incident location' 'On motorway / elevated road'
 'In street remote from gazetteer location' 'Within same building'
 'Nearby address - street not listed in gazetteer'
 'Nearby address - no building in street' 'Railway land or rolling stock'
 nan]
FRS ['London']
Month [ 1  2  3  4  5  6  7  8  9 10 11 12]
DayOfWeek [3 4 5 6 0 1 2]
DayName ['Thursday' 'Friday' 'Saturday' 'Sunday' 'Monday' 'Tuesday' 'Wednesday']

In [18]:
# df[df["Postcode_full"].isna()].head(30)
print(df.SpecialServiceType.unique())
print(df.Postcode_district.value_counts())

['RTC' 'Assist other agencies' nan 'Flooding' 'Medical Incident'
 'Lift Release' 'No action (not false alarm)' 'Effecting entry/exit'
 'Animal assistance incidents' 'Other rescue/release of persons'
 'Making Safe (not RTC)' 'Other Transport incident' 'Evacuation (no fire)'
 'Spills and Leaks (not RTC)' 'Removal of objects from people'
 'Hazardous Materials incident' 'Advice Only' 'Water provision'
 'Rescue or evacuation from water' 'Suicide/attempts' 'Stand By'
 'Medical Incident - Co-responder']
Postcode_district
CR0     34799
SE1     29315
E1      27133
NW1     25192
E14     24398
N1      24287
NW10    20497
E17     18624
SE18    18363
W2      17752
SW6     17380
NW3     16316
SE15    16200
N17     15101
NW6     15009
N16     14930
E3      14876
E2      14763
SE5     14216
SW11    14086
SW16    13750
IG11    13445
N7      13186
SW19    12959
W12     12923
SE16    12821
W3      12765
E15     12764
E8      12734
E6      12479
E16     12237
NW2     12109
E9      12042
SW9     11924
SE13    11912
NW8     11670
SW15    11607
SW17    11582
W6      11573
W10     11545
SW2     11498
EN3     11436
E11     11391
W11     11020
E5      10967
N4      10909
IG1     10815
SW3     10570
W9      10457
BR1     10177
SE6     10133
SW4     10062
UB3      9820
N15      9748
E4       9713
NW9      9674
SW1V     9535
SE9      9517
CR4      9464
N9       9381
SW8      9269
SE17     9254
HA8      9187
HA3      9186
W5       9072
E13      9063
TW6      8984
SW18     8973
SE8      8795
BR5      8410
W14      8326
UB8      8310
N19      8301
N22      8268
HA9      8238
DA8      8054
SE10     8037
E10      7995
W4       7897
CR7      7759
RM10     7628
UB5      7554
HA1      7541
SE11     7504
N18      7453
RM3      7452
EC1V     7347
NW5      7324
EN1      7299
N8       7290
BR3      7288
SM1      7282
E7       7273
EN5      7020
UB6      6991
SE25     6788
SE23     6739
UB1      6737
UB7      6615
TW13     6464
RM13     6459
SE26     6455
KT1      6455
TW3      6397
BR2      6375
RM9      6291
SW7      6248
BR6      6242
TW7      6161
SE14     6144
HA4      6130
EN2      6103
HA2      5946
NW11     5923
SM5      5905
SW1P     5873
W8       5863
SW5      5858
CR2      5711
HA0      5698
SM6      5629
RM8      5587
NW4      5563
SE3      5545
IG8      5493
UB4      5414
SW10     5396
SE12     5391
W13      5389
KT2      5348
SE28     5321
DA14     5291
E12      5251
RM7      5237
IG3      5225
SE27     5188
RM1      5178
TW14     5167
UB2      5130
TW9      5125
TW8      5100
SW12     5092
SE19     5082
SE2      5052
W1S      5010
HA7      4983
KT3      4948
SE20     4899
N12      4777
RM6      4759
KT6      4711
W1D      4687
HA5      4658
CR8      4658
SE4      4583
SE22     4415
N11      4356
SW1X     4355
SE7      4352
SW1W     4329
WC2H     4277
W1J      4275
UB10     4271
TW5      4234
WC1H     4196
W1U      4130
SW1Y     4075
N5       4075
W1T      4064
W1F      4064
N13      4061
NW7      4060
WC1X     4056
WC1N     4040
IG6      4038
W7       4037
N2       3977
N14      3942
SM4      3901
W1K      3891
N3       3853
SM2      3840
W1W      3747
TW2      3736
TW4      3707
TW1      3654
N10      3644
RM12     3623
DA17     3582
SE24     3578
RM11     3490
SW20     3487
W1G      3468
IG2      3367
TW10     3313
N6       3239
EN4      3149
DA7      3117
HA6      3080
RM14     3077
WC2B     3064
EC1R     3060
TW11     3057
DA16     3043
TW12     3027
WC1E     2942
E1W      2900
W1B      2869
SE21     2853
WC2E     2820
EC2A     2794
W1H      2719
WC2N     2656
SM3      2590
BR7      2547
E18      2536
KT9      2529
DA1      2527
DA6      2523
CR5      2515
N20      2509
EC1M     2404
KT5      2398
SW1A     2346
W1C      2321
DA15     2301
N21      2206
SW13     2205
EC1N     2096
EC1Y     2080
IG5      2056
DA5      2000
RM5      1994
SW14     1944
EC1A     1879
UB9      1833
BR4      1793
KT4      1682
TN16     1635
WC2R     1613
RM2      1566
EC2M     1562
WC1B     1448
E20      1419
EC3V     1400
SW1H     1382
CR9      1341
DA18     1281
EC4N     1280
WC1V     1219
IG4      1195
SW1E     1190
EC3N     1123
EC4V     1058
EC2R     1039
EC4A     1037
EC2V     1035
IG7      1006
N1C       974
EC4M      968
WC2A      931
EC2Y      917
EC4Y      862
WC1A      849
EC2N      848
EC3A      828
EC3M      826
EC3R      783
EC4R      685
WC1R      589
TW19      568
UB11      495
RM4       386
KT8       373
EN8       361
TW15      179
BR8       173
W1A       161
SL3       132
EN7       126
TN14      116
SM7       111
CM14       94
CR6        91
IG9        82
WD6        82
EN6        77
CR3        72
EC3P       53
EC2P       46
WD3        29
CM13       29
TW16       24
RM15       20
W1X        18
KT22       15
KT18       14
KT17       14
W1V        14
WD23       14
KT19       12
W15        11
SL0        10
EN9         8
BF1         6
E98         5
W1M         4
SW99        3
RM19        3
SE1P        3
EC1P        3
W17         2
EC1         2
WC2         2
EC47        2
W1          2
W1N         2
E77         1
RM16        1
W16         1
E4A         1
EC17        1
EC2         1
W1P         1
CR44        1
WC14        1
WD19        1
EC4B        1
OX9         1
E22         1
Name: count, dtype: int64

In [19]:
df.to_csv("../data/Incidents.csv", sep=";")